version: '3.9'

networks:
  fitness-training-apps-network:
    driver: bridge

volumes:
  mongodb_data:
  elasticsearch-data:

services:
  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:8080'
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_URL=${DB_CONNECTION_URL}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - REGION=${REGION}
      - BUCKET_NAME=${BUCKET_NAME}
      - ENDPOINT=${ENDPOINT}
    volumes:
      - '.:/app'
    networks:
      - fitness-training-apps-network
    depends_on:
      - mongodb

  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      AUTH: admin
    ports:
      - '27017:27017'
    networks:
      - fitness-training-apps-network
    volumes:
      - mongodb_data:/data/db

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - '8081:8081'
    networks:
      - fitness-training-apps-network
    depends_on:
      - mongodb

  # Elastic Search
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m' # 1GB of memory allocated to JVM  heap size
    ports:
      - '9200:9200' # Expose Elasticsearch HTTP port
      - '9300:9300' # Expose Elasticsearch TCP transport port
    networks:
      - fitness-training-apps-network
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch

  # Kibana
  kibana:
    image: kibana:7.9.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - fitness-training-apps-network
    depends_on:
      - elasticsearch
